# Generated by Django 2.0.2 on 2018-02-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("threesixty", "0002_survey_is_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="participant_can_skip",
            field=models.BooleanField(
                default=False,
                help_text="This option allows a participant of this survey to skip single questions.",
                verbose_name="participant can skip",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="decision",
            field=models.NullBooleanField(verbose_name="decision"),
        ),
    ]
